# Gradle settings
org.gradle.parallel = true
org.gradle.jvmargs = -Xmx4096M
org.gradle.daemon = false
# Plugin versions
NeoGradle = 7.0.+
SpongePoweredMixin = 0.7.+
Licenser = 0.6.0
CurseForge = 0.6.1
# Minecraft
MinecraftVersion = 1.21.8
MinecraftVersionRange = [1.21.8,1.22)
# NeoForge
NeoForgeVersion = 21.8.39
NeoForgeVersionRange = [21.8,)
NeoForgeLoaderRange = [4,)
# XOres
# Version in the format [major_minecaft].[minor_minecaft].[feature/bugfix]
ModVersion = 4.3.2
