modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory

license="All rights reserved"

[[mods]] #mandatory

modId="xores" #mandatory

version="1.18.1-1.0" #mandatory

displayName="XBackpack" #mandatory

credits="Thanks for downloading my Mod" #optional

authors="Luis" #optional

#displayURL="https://github.com/Luis-st/Forge-1.18.1-XOres/issues"

description='''

Have a lot of fun when playing
XOres Development Team
'''

[[dependencies.xores]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[39,)" #mandatory

    ordering="NONE"

    side="BOTH"
    
[[dependencies.xores]]

    modId="minecraft"
    
    mandatory=true
    
    versionRange="[1.18.1,1.19)"
    
    ordering="NONE"
    
    side="BOTH"
