modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="xores"
version="1.19-1.5"
displayName="XOres"
credits="Thanks for downloading my Mod"
authors="Luis"
displayURL="https://github.com/Luis-st/Forge-XOres/issues"
description='''
XOres adds a few new Ores and Tools
Ores:
 - Jade
 - Saphire
 - Limonite
 - Rosite
 - Enderite
 
Tools:
 - Blazing
 - Rose Quartz
 - Steel
 - Night

Have a lot of fun when playing
XOres Development Team
'''

[[dependencies.xores]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
    
[[dependencies.xores]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
